# Generated by Django 4.2.5 on 2023-10-07 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_receita_remove_despesa_data_despesa_data_fim_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='despesa',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='despesa',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='receita',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='receita',
            name='usuario',
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
        migrations.DeleteModel(
            name='Despesa',
        ),
        migrations.DeleteModel(
            name='Receita',
        ),
    ]
