# Generated by Django 4.2.5 on 2023-10-14 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_remove_despesa_categoria_remove_despesa_usuario_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
