# Generated by Django 4.2.5 on 2023-10-10 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0002_despesa'),
    ]

    operations = [
        migrations.AddField(
            model_name='despesa',
            name='categoria',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
