# Generated by Django 4.2.5 on 2023-10-14 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meta',
            name='tipo_prazo',
            field=models.CharField(max_length=20),
        ),
    ]
